- hosts: backend
  become: yes
  tasks:

    - name: Install Packages
      become: yes
      raw: |
        yum install -y docker python3-pip

    - name: Install 'requests' for Ansible docker modules
      become: yes
      pip:
        name: 
          - docker
          - urllib3<2.0
          - requests
        executable: pip3


    - name: Ensure Docker is started
      become: yes
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull backend image from Docker Hub
      become: yes
      docker_image:
        name: transcendentalguy/barebones-backend:latest
        source: pull

    - name: Run backend container
      become: yes
      docker_container:
        name: backend-app
        image: transcendentalguy/barebones-backend:latest
        state: started
        restart_policy: always
        published_ports:
          - "5000:5000"
        env:
          DB_HOST: "{{ (lookup('file', 'tf_outputs.json') | from_json).database_private_ip.value }}"
          DB_NAME: minimal_app
          DB_USER: app_user
          DB_PASSWORD: S3cureP@ssw0rd
