- hosts: database
  become: yes
  vars:
    db_name: minimal_app
    db_user: app_user
    db_password: S3cureP@ssw0rd
  tasks:
    - name: Install Docker
      raw: |
        yum install -y docker python3-pip

    - name: Install requests + Docker SDK
      pip:
        name:
          - docker
          - requests
          - urllib3<2.0
        executable: pip3

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull PostgreSQL image
      docker_image:
        name: postgres
        tag: "14"
        source: pull

    - name: Copy init.sql to remote host
      copy:
        src: "{{ playbook_dir }}/database/init_script.sql"
        dest: /tmp/init.sql
        mode: '0644'

    - name: Run PostgreSQL container
      docker_container:
        name: postgres-db
        image: postgres:14
        state: started
        restart_policy: always
        env:
          POSTGRES_DB: "{{ db_name }}"
          POSTGRES_USER: "{{ db_user }}"
          POSTGRES_PASSWORD: "{{ db_password }}"
        published_ports:
          - "5432:5432"
        volumes:
          - /var/lib/postgresql/data:/var/lib/postgresql/data
          - /tmp/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro