- hosts: frontend
  become: yes
  tasks:
    - name: Install Docker
      become: yes
      raw: |
        yum install -y docker python3-pip

    - name: Install 'requests' for Ansible docker modules
      become: yes
      pip:
        name: 
          - docker
          - urllib3<2.0
          - requests
        executable: pip3

    - name: Ensure Docker is started
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Stop and remove any existing frontend container
      docker_container:
        name: barebones-frontend
        state: absent

    - name: Pull frontend image from Docker Hub
      docker_image:
        name: transcendentalguy/barebones-frontend:latest
        source: pull
        force_source: true

    - name: Run frontend container
      docker_container:
        name: barebones-frontend
        image: transcendentalguy/barebones-frontend:latest
        state: started
        restart_policy: always
        published_ports:
          - "8080:8080"
        env:
          BACKEND_URL: "http://{{ (lookup('file', 'tf_outputs.json') | from_json).backend_ip.value }}:5000"
